---
title: "Exploratory plots"
author: "ajpelu"
date: "2022-08-30"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
opts_chunk$set(echo = TRUE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = TRUE,
               comment = NA,
               message = FALSE,
               warning = FALSE,
               autodep = TRUE)
```

```{r,message=FALSE}
source("code/load_pkgs.R")
source("code/aux_functions.R")
```

```{r}
d <- read_csv(here::here("data/cleaned_data.csv"))
colores <- c("dodgerblue4", "goldenrod1")
```


## Explore differences among commons and transhumance for vegetation parameters and other interest variables 

```{r plot-mean}
vi <- c("shannon", "riqueza", "fitovol_dm3", 
        "rec_total_porc", "rec_vegetal_porc",
        "tasa_cons", "estiercol_kg_ha")

data_mean <- d |> 
  dplyr::select(one_of(vi), commonsSort, transh) |>
  pivot_longer(-c(commonsSort, transh)) |> 
  group_by(name, commonsSort, transh) |> 
  summarise(
    mean = mean(value, na.rm=TRUE),
    sd = sd(value, na.rm = TRUE), 
    se = plotrix::std.error(value, na.rm = TRUE)
  ) |>
  mutate(nameF = recode_factor(name, 
                        estiercol_kg_ha = "Estiercol~(kg~ha^{-1})",
                        fitovol_dm3 = "Fitovolumen~(m^3)",
                        rec_total_porc = "Total~Coverage~('%')", 
                        rec_vegetal_porc = "Plant~Coverage~('%')",
                        riqueza = "Richness~(species~number)",
                        shannon = "Shannon~index",
                        tasa_cons = "Consumption~rate")) |> 


  mutate(commonsF = recode_factor(commonsSort, 
                           '0_Castril' = "Castril",
                           '1_Santiago' = "Santiago",
                           '2_Pontones' = "Pontones"))


data_mean %>% 
  ggplot(aes(y = mean, x = commonsF, group = transh, colour = transh)) + 
  geom_point(size = 2) + 
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = .15) + 
  geom_line() + 
  facet_wrap(~nameF, scales = "free_y", labeller = label_parsed) + 
  theme_bw() + 
  theme(
    strip.background = element_blank(),
    panel.grid = element_blank(),
    legend.position = "top"
  ) +
  labs(x = "", y = "") + 
  scale_colour_manual("Transhumance", values = colores) + 
  guides(color = guide_legend(direction = "horizontal"))
```


## Explore the variation of the covariates among the commons and transhumance 
```{r plot-covariates}
covs <- c("sr.win", "sr.spr", "sr.sum","sr.aut","altitud_m","cic","fosforo","mo","ph", "potasio","nitrogeno","carbono")      

covariates_mean <- d %>% 
  dplyr::select(one_of(covs), commonsSort, transh) %>% 
  pivot_longer(-c(commonsSort, transh)) %>% 
  group_by(name, commonsSort, transh) %>% 
  summarise(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE), 
    se = plotrix::std.error(value, na.rm = TRUE)
  ) %>% 
  mutate(commonsF = recode_factor(commonsSort, 
                           "0_Castril" = "Castril",
                           "1_Santiago" = "Santiago",
                           "2_Pontones" = "Pontones"))
    
covariates_mean %>% 
  ggplot(aes(y = mean, x = commonsF, group = transh, colour = transh)) + 
  geom_point(size = 2) + 
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = .15) + 
  geom_line() + 
  facet_wrap(~name, scales = "free_y") + 
  theme_bw() + 
  theme(
    strip.background = element_blank(),
    panel.grid = element_blank(),
    legend.position = "top"
  ) +
  labs(x = "", y = "") + 
  scale_colour_manual("Transhumance", values = colores) + 
  guides(color = guide_legend(direction = "horizontal"))
  
```


